"""initial schema

Revision ID: 1c45786d23ab
Revises: 
Create Date: 2026-06-01 20:00:55.489667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c45786d23ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('asset_class', sa.String(length=30), nullable=True),
    sa.Column('timeframe', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sharpe_backtest', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('asset_class_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_argentine', sa.Boolean(), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=30), nullable=True),
    sa.Column('ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_class_id'], ['asset_classes.id'], ),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_currency', sa.String(length=5), nullable=False),
    sa.Column('risk_profile', sa.String(length=20), nullable=False),
    sa.Column('preferred_markets', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('notification_email', sa.Boolean(), nullable=False),
    sa.Column('notification_telegram', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('notification_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=30), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('timeframe', sa.String(length=5), nullable=True),
    sa.Column('scanner_source', sa.String(length=30), nullable=True),
    sa.Column('scanner_rank', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=30), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('market_regime', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ml_probability_bull', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ml_probability_bear', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reward_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expected_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('risk_reward', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('take_profit_1', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('take_profit_2', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('technical_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fundamental_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidation_reason', sa.Text(), nullable=True),
    sa.Column('is_executed', sa.Boolean(), nullable=False),
    sa.Column('execution_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('pnl_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('backtest_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_signal_active', 'ai_signals', ['is_active'], unique=False)
    op.create_index('ix_ai_signal_active_confidence', 'ai_signals', ['is_active', 'confidence'], unique=False)
    op.create_index('ix_ai_signal_confidence', 'ai_signals', ['confidence'], unique=False)
    op.create_index('ix_ai_signal_scanner_rank', 'ai_signals', ['scanner_rank'], unique=False)
    op.create_index('ix_ai_signal_symbol_generated', 'ai_signals', ['symbol', 'generated_at'], unique=False)
    op.create_index(op.f('ix_ai_signals_symbol'), 'ai_signals', ['symbol'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_ai_signals_symbol'), table_name='ai_signals')
    op.drop_index('ix_ai_signal_symbol_generated', table_name='ai_signals')
    op.drop_index('ix_ai_signal_scanner_rank', table_name='ai_signals')
    op.drop_index('ix_ai_signal_confidence', table_name='ai_signals')
    op.drop_index('ix_ai_signal_active_confidence', table_name='ai_signals')
    op.drop_index('ix_ai_signal_active', table_name='ai_signals')
    op.drop_table('ai_signals')
    op.drop_table('watchlists')
    op.drop_table('user_sessions')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('users')
    op.drop_table('exchanges')
    op.drop_table('asset_classes')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
