"""add model_id to ai_signals

Revision ID: a367b336e386
Revises: 1c45786d23ab
Create Date: 2026-06-03 21:39:15.800182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a367b336e386'
down_revision: Union[str, None] = '1c45786d23ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_asset_symbol_exchange', 'assets', ['symbol', 'exchange_id'], unique=False)
    op.create_unique_constraint('uq_asset_symbol_exchange', 'assets', ['symbol', 'exchange_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_asset_symbol_exchange', 'assets', type_='unique')
    op.drop_index('ix_asset_symbol_exchange', table_name='assets')
    # ### end Alembic commands ###
