"""add portfolios

Revision ID: f0ccb3672a62
Revises: a367b336e386
Create Date: 2026-06-06 18:03:57.330039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0ccb3672a62'
down_revision: Union[str, None] = 'a367b336e386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('alert_name', sa.String(length=100), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('condition_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('condition_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('timeframe', sa.String(length=5), nullable=True),
    sa.Column('channels', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('repeat', sa.Boolean(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('triggered_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channels_sent', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('was_delivered', sa.Boolean(), nullable=False),
    sa.Column('delivery_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_events')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
